# 개발 환경 설정
app:
  prefix: '/api'
  port: 8082
  logger:
    # 프로젝트 로그 저장 경로, 상대 경로(상대 프로젝트 루트) 또는 절대 경로
    dir: '. ./logs'
  # 파일 관련
  file:
    # location 파일 업로드 후 저장 디렉터리, 상대 경로(상대 본 프로젝트 루트 디렉터리) 또는 절대 경로
    location: '. ./upload'
    # 파일 서버 주소입니다. 개발 환경 설정입니다. 생산 환경은 도메인 네임으로 설정하십시오.
    domain: 'http://localhost:8081'
    # 파일 가상 경로로 시작하려면 / 로 시작해야 합니다
    serveRoot: '/static'
# 데이터베이스 설정
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'kapok'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 설정
redis:
  host: 'localhost'
  port: 6379
  db: 0
  keyPrefix: 'nest:'

# jwt 설정
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 권한 화이트리스트 설정
perm:
  router:
    whitelist: [{ path: '/api/register', method: 'POST'  }, { path: '/api/login', method: 'POST' }, { path: '/api/perm/{id}', method: 'GET' }, { path: '/api/oss/upload', method: 'POST' }]

# 사용자 관련
# 초기 비밀번호, 비밀번호 초기화
user:
  initialPassword: 'Q123456'